version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - F:/proc:/project
    ports:
      - 80:8501
    restart: always
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - ./database/.env
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
